# Generated by Django 5.2.7 on 2025-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type_name',
            field=models.CharField(default='job_seeker', max_length=50),
        ),
    ]
